export type Stack = (
  | "nextjs"
  | "tailwindcss"
  | "firebase"
  | "android"
  | "dotnet"
  | "mongodb"
  | "expressjs"
  | "reactjs"
  | "html"
  | "css"
  | "javascript"
  | "python"
  | "jquery"
  | "typescript"
)[];